version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    command:
      -  --mysql-native-password=ON
    ports:
#      port windows: port container
      - "5430:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: voll_med
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: